include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors       # なるべくconstを使う
    - avoid_print                     # print()の代わりに、debugPrint()を使う
    - unnecessary_null_checks         # いらないnullチェックとおさらば
    - always_use_package_imports      # 相対パスimportを禁止
    - prefer_double_quotes            # 文字列にダブルクオートを使う
    - sort_pub_dependencies           # pubspec.yaml の依存関係をアルファベット順に整理