name: prototype_v1
description: "メシイクのプロトタイプ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  app_settings: ^5.2.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_map: ^8.0.0
  flutter_map_animations: ^0.9.0
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  retrofit: ^4.4.2


dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true